import type { Climb } from '@/types'

export const EXAMPLE_CLIMBS: Climb[] = [
  {
    id: '1',
    user_id: 'demo-user',
    created_at: '2026-01-04T10:30:00Z',
    location: 'Gravity Lab',
    climb_type: 'boulder',
    grade_scale: 'color_circuit',
    grade_value: 'Yellow',
    hold_color: 'yellow',
    style: ['Overhang', 'Crimp'],
    outcome: 'Fail',
    awkwardness: 4,
    failure_reasons: ['Finger Strength', 'Beta Error'],
    notes: 'Fell at the crux, need to work on left-hand crimp sequence',
  },
  {
    id: '2',
    user_id: 'demo-user',
    created_at: '2026-01-03T18:45:00Z',
    location: 'The Rock Club',
    climb_type: 'boulder',
    grade_scale: 'v_scale',
    grade_value: 'V4',
    hold_color: 'green',
    style: ['Vert', 'Sloper'],
    outcome: 'Sent',
    awkwardness: 2,
    failure_reasons: ['Bad Feet'],
    notes: 'Felt good, sloper crux was tricky but figured out the beta',
  },
  {
    id: '3',
    user_id: 'demo-user',
    created_at: '2026-01-02T14:20:00Z',
    location: 'Stone Summit',
    climb_type: 'sport',
    grade_scale: 'font',
    grade_value: '6b+',
    hold_color: 'blue',
    style: ['Slab', 'Vert'],
    outcome: 'Fail',
    awkwardness: 5,
    failure_reasons: ['Fear', 'Commitment'],
    notes: 'Sketched out at the clip, pumped out trying to hang',
  },
  {
    id: '4',
    user_id: 'demo-user',
    created_at: '2026-01-01T16:00:00Z',
    location: 'Gravity Lab',
    climb_type: 'boulder',
    grade_scale: 'color_circuit',
    grade_value: 'Red',
    hold_color: 'red',
    style: ['Overhang', 'Pinch'],
    outcome: 'Fail',
    awkwardness: 3,
    failure_reasons: ['Pumped', 'Core'],
    notes: 'Core was weak on the roof section, need more core work',
  },
  {
    id: '5',
    user_id: 'demo-user',
    created_at: '2025-12-31T19:30:00Z',
    location: 'The Rock Club',
    climb_type: 'boulder',
    grade_scale: 'v_scale',
    grade_value: 'V6',
    hold_color: 'purple',
    style: ['Dyno', 'Sloper'],
    outcome: 'Sent',
    awkwardness: 1,
    failure_reasons: [],
    notes: 'Flow state! Dyno felt effortless',
  },
  {
    id: '6',
    user_id: 'demo-user',
    created_at: '2025-12-30T11:00:00Z',
    location: 'Stone Summit',
    climb_type: 'sport',
    grade_scale: 'font',
    grade_value: '7a',
    hold_color: 'orange',
    style: ['Overhang', 'Crimp'],
    outcome: 'Fail',
    awkwardness: 4,
    failure_reasons: ['Body Position', 'Precision'],
    notes: 'Couldnt find the right body position on the overhang crux',
  },
  {
    id: '7',
    user_id: 'demo-user',
    created_at: '2025-12-29T15:15:00Z',
    location: 'Gravity Lab',
    climb_type: 'boulder',
    grade_scale: 'color_circuit',
    grade_value: 'Black',
    hold_color: 'black',
    style: ['Roof', 'Pinch'],
    outcome: 'Fail',
    awkwardness: 5,
    failure_reasons: ['Finger Strength', 'Power', 'Beta Error'],
    notes: 'Projecting this one, roof is absolutely savage',
  },
  {
    id: '8',
    user_id: 'demo-user',
    created_at: '2025-12-28T20:45:00Z',
    location: 'The Rock Club',
    climb_type: 'boulder',
    grade_scale: 'v_scale',
    grade_value: 'V3',
    hold_color: 'pink',
    style: ['Vert', 'Sloper', 'Slab'],
    outcome: 'Sent',
    awkwardness: 2,
    failure_reasons: ['Focus'],
    notes: 'Lost focus once but recovered quickly',
  },
]
